/*
 * $Header: /u1/colin/lucifer/8bit/gen/RCS/machine.h,v 1.1 89/09/28 13:50:22 colin Exp $
 *
 * Defines for ID bytes of all supported machine types
 *
 * $Log:	machine.h,v $
 * Revision 1.1  89/09/28  13:50:22  colin
 * Initial revision
 * 
 */

#define ID_M6801	0x01	/* Motorola 6801 */
#define ID_M68HC11	0x02	/* Motorola 68HC11 */
#define ID_H6301	0x03	/* Hitachi 6301/6303 */
#define ID_M6809	0x04	/* Motorola 6809 */
#define ID_Z80		0x05	/* Zilog Z80 */
#define ID_I8086	0x06	/* Intel 8086 family */
#define ID_I80286	0x07	/* Intel 80286 */
#define ID_I80386	0x08	/* Intel 80386 */
#define ID_I8051	0x09	/* Intel 8051 */
#define ID_I8096	0x0A	/* Intel 8096 */
#define ID_M68000	0x0B	/* Motorola 68000 */
#define ID_W65802	0x0C	/* Western Design Center 65802 */
#define ID_W65816	0x0D	/* Western Design Center 65816 */

